#!/usr/bin/env python
import rospy
from std_msgs.msg import Byte
global Value
def callback(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %d", data.data) 
    Value = data.data
    if Value == 1 :
        rospy.loginfo(Value)
    #if(value.data == 1)rospy.loginfo("oke ,%d",value.data)     
def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("button", Byte, callback)
    rospy.spin()
   
if __name__ == '__main__':
    listener()